# Generated by Django 2.2.10 on 2020-02-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the thing was first created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When the thing was last modified.')),
            ],
        ),
    ]
