# Generated by Django 2.2.10 on 2020-02-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrosat_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_celery', models.BooleanField(default=True, help_text='Enable the task management system.')),
            ],
            options={
                'verbose_name': 'Task Settings',
                'verbose_name_plural': 'Task Settings',
            },
        ),
    ]
